from os import environ
from mongoengine import connect
from hashlib import sha256

from Regions.region import Region

if __name__ == '__main__':
        regions = ['BOGOTA', 'VALLE', 'ANTIOQUIA', 'CARTAGENA', 'HUILA', 'META', 
            'RISARALDA', 'NORTE SANTANDER', 'CALDAS', 'CUNDINAMARCA', 'BARRANQUILLA', 'SANTANDER',
            'QUINDIO', 'TOLIMA', 'CAUCA', 'STA MARTA D.E.', 'CESAR', 'SAN ANDRES', 'CASANARE',
            'NARIÑO', 'ATLANTICO', 'BOYACA', 'CORDOBA', 'BOLIVAR', 'SUCRE', 'MAGDALENA', 'GUAJIRA', 
            'CHOCO', 'AMAZONAS', 'CAQUETA', 'PUTUMAYO', 'ARAUCA', 'VAUPES', 'GUAINIA', 'VICHADA', 'GUAVIARE', 'Tolima', 
            'BOGOTA', 'BUGA', 'MEDELLIN', 'ITAGUI', 'CARTAGENA', 'NEIVA', 'PALMIRA', 'VILLAVICENCIO', 
            'RIONEGRO', 'CALI', 'DOSQUEBRADAS', 'CUCUTA', 'MANIZALES', 'SUBACHOQUE', 'SOACHA', 'BARRANQUILLA', 'FLORIDABLANCA', 'ARMENIA',
            'PEREIRA', 'CAJICA', 'IBAGUE', 'BUCARAMANGA', 'POPAYAN', 'VITERBO', 'ANAPOIMA', 'LA ESTRELLA', 'ENVIGADO', 
            'SANTA MARTA', 'CHIA', 'MADRID', 'VILLA DEL ROSARIO', 'CARTAGO', 'YUMBO', 'GUARNE', 'BELLO', 'CALARCA', 'VALLEDUPAR', 'LA DORADA', 'CHINCHINA', 'SAN ANDRES',
            'YOPAL', 'GUATAPE', 'COTA', 'SABANETA', 'VILLAMARIA', 'TRUJILLO', 'PACHO', 'RETIRO', 'APARTADO', 'CACERES', 'IPIALES', 'LOS PATIOS', 'MOSQUERA', 'LA UNION', 
            'FUSAGASUGA', 'LA CALERA', 'VILLETA', 'PALERMO', 'SAN PEDRO', 'DARIEN', 'FUNZA', 'TULUA', 'SOLEDAD', 'EL DOVIO', 'SANTANA', 'FRONTINO', 'TUNJA', 'TOCANCIPA',
            'PUERTO COLOMBIA', 'SAHAGUN', 'PASTO', 'POLO NUEVO', 'VILLAPINZON', 'MONTEBELLO', 'MONTENEGRO', 'SANTA ROSA DE OSOS', 'TURBACO', 'SINCELEJO', 'LA CEJA', 
            'SAN FRANCISCO', 'MONTERIA', 'OICATA', 'ARJONA', 'SOPO', 'CIENAGA', 'TUMACO', 'RIOHACHA', 'ZIPAQUIRA', 'PUERTO SANTANDER', 'TOGUI', 'CUMBAL', 'ULLOA', 
            'SANTANDER DE QUILICHAO', 'FILANDIA', 'CIRCASIA', 'ANSERMA', 'DON MATIAS', 'CALDAS', 'CHOACHI', 'COCORNA', 'GUACARI', 'TENJO', 'BUENAVENTURA', 'ACACIAS', 
            'BARRANCABERMEJA', 'SAN JUAN DE RIO SECO', 'ANGOSTURA', 'GUACHENÉ', 'PONEDERA', 'SANTO TOMAS', 'GALAPA', 'CIENAGA DE ORO', 'SANTA ROSA DE CABAL', 'LA TEBAIDA', 'MIRANDA', 
            'JAMUNDI', 'COPACABANA', 'TENZA', 'GINEBRA', 'ANDALUCIA', 'GARAGOA', 'SANTA SOFIA', 'FACATATIVA', 'CONTADERO', 'CUMBITARA', 'OCAÑA', 'CIMITARRA', 'CONCEPCION', 'CURITI', 
            'ESPINAL', 'SOCHA', 'TIMBIO', 'SAN DIEGO', 'GIRARDOT', 'BUGALAGRANDE', 'UBATE', 'SANTUARIO', 'FLORIDA', 'COGUA', 'SOGAMOSO', 'CERETE', 'TIERRALTA', 'SUESCA', 'AGRADO', 
            'GIGANTE', 'PITALITO', 'QUIBDO', 'CANDELARIA', 'EL CERRITO', 'YOTOCO', 'ZONA BANANERA', 'BARANOA', 'MALAMBO', 'SAN PEDRO DE URABA', 'MELGAR', 'SAN CRISTOBAL', 'ANDES', 
            'SAN MARTIN', 'LA VIRGINIA', 'GRANADA', 'SONSON', 'TUQUERRES', 'PUERTO TEJADA', 'EL BANCO', 'BARRANCO DE LOBA', 'LETICIA', 'FLORENCIA', 'ACEVEDO', 'TIMANA', 
            'ISNOS (SAN JOSE DE ISNOS)', 'RIVERA', 'GARZON', 'SAN AGUSTIN', 'VIJES', 'AQUITANIA', 'AIPE', 'EL COLEGIO', 'CALAMAR', 'UNION PANAMERICANA', 'LORICA', 'SABANAGRANDE', 'GUADUAS', 
            'SIBATE', 'PIEDECUESTA', 'BARBOSA', 'SANTA ROSA', 'LA CUMBRE', 'BOSCONIA', 'CUASPUD (CARLOSAMA)', 'VILLARICA', 'ROBLES (LA PAZ)', 'RIO DE ORO', 'NATAGA', 'PUEBLOVIEJO', 
            'AGUSTIN CODAZZI', 'AGUACHICA', 'EL TAMBO', 'ALCALA', 'MANATI', 'TOLEDO', 'GUAMO', 'BELEN', 'PAICOL', 'POTOSI', 'SAN JUAN DE ARAMA', 'PAZ DE ARIPORO', 'LA PLATA', 'CALOTO', 
            'DAGUA', 'SAMANA', 'MAICAO', 'ALBANIA', 'SAN JUAN DEL CESAR', 'ALGECIRAS', 'RISARALDA', 'CHIQUINQUIRA', 'SABANALARGA', 'CUBARA', 'CANALETE', 'VILLA DE LEYVA', 'DUITAMA', 
            'SAMACA', 'LA FLORIDA', 'GUACHUCAL', 'OPORAPA', 'ANCUYA', 'ROLDANILLO', 'CACOTA', 'ABREGO', 'TIBU', 'MARMATO', 'MARQUETALIA', 'LA JAGUA DE IBIRICO', 'CHIRIGUANA', 
            'PALMAR DE VARELA', 'DISTRACCION', 'CHIPAQUE', 'PUERTO NARIÑO', 'TURBANA', 'TURMEQUE', 'PIENDAMO', 'MARIA LA BAJA', 'RESTREPO', 'NORCASIA', 'CARMEN DE VIBORAL', 
            'LINARES', 'PAIPA', 'UNE', 'FOMEQUE', 'MAGANGUE', 'SILVANIA', 'LOS PALMITOS', 'SANTA LUCIA', 'MONTELIBANO', 'VILLANUEVA', 'RIOSUCIO', 'GACHANCIPA', 'PUERTO LEGUIZAMO',
            'MAGUI (PAYAN)', 'MONIQUIRA', 'PAMPLONA', 'ROVIRA', 'FONSECA', 'SINCE', 'CAMPOALEGRE', 'SANTA ROSA DE VITERBO', 'CORDOBA', 'MUZO', 'CISNEROS', 'LA TOLA', 'TINJACA', 
            'SITIO NUEVO', 'PUERTO GUZMAN', 'PROVIDENCIA', 'PLANADAS', 'PRADERA', 'ARAUCA', 'AGUADAS', 'ITUANGO', 'MEDIO BAUDO (BOCA DE PEPE)', 'EL ZULIA', 'PUERTO LOPEZ', 'MITU', 
            'EL RETEN', 'ITSMINA', 'MIRAFLORES', 'VIRACACHA', 'CUCAITA', 'SAN VICENTE DEL CAGUAN', 'REPELON', 'QUIMBAYA', 'BUENOS AIRES', 'EL BAGRE', 'PUERTO GAITAN', 'SANTA CATALINA',
            'TOTORO', 'DIBULLA', 'LA CRUZ', 'PUERTO ASIS', 'TURBO', 'SALADOBLANCO', 'ARACATACA', 'FUNDACION', 'SAN LUIS', 'CAUCASIA', 'TABIO', 'SUTAMARCHAN', 'MANZANARES', 'MANAURE', 
            'TIPACOQUE', 'COMBITA', 'SAN CARLOS DE GUAROA', 'NILO', 'JUAN DE ACOSTA', 'PIVIJAY', 'CAMPO DE LA CRUZ', 'FLANDES', 'SOCORRO', 'VENTAQUEMADA', 'TADO', 'RIOQUITO', 'LIBANO',
            'GONZALEZ', 'PAYA', 'ATRATO', 'RIO IRO', 'BAHIA SOLANO (MUTIS)', 'LURUACO', 'PASCA', 'MORROA', 'PIEDRAS', 'CLEMENCIA', 'BAGADO', 'CHINU', 'MARINILLA', 'USIACURI', 'PALESTINA',
            'SAN MIGUEL DE SEMA', 'MALLAMA (PIEDRANCHA)', 'HONDA', 'TIMBIQUI', 'TUBARA', 'BOJAYA (BELLAVISTA)', 'GUATEQUE', 'EL PASO', 'BECERRIL', 'CABUYARO', 'COPER', 'CAQUEZA', 
            'CHOCONTA', 'JUNIN', 'LA MESA', 'SAN ANTONIO DE TEQUENDAMA', 'LENGUAZAQUE', 'TAURAMENA', 'SESQUILE', 'VALLE DEL GUAMUEZ', 'MOCOA', 'ORITO', 'EL COPEY', 
            'OLAYA HERRERA(BOCAS DE SATINGA', 'SAN PABLO', 'EL PIÑON', 'CAREPA', 'PAUNA', 'ZIPACON', 'LA PLAYA', 'ARGELIA', 'PIOJO', 'SAN ONOFRE', 'COROZAL', 
            'FRANCISCO PIZARRO (SALAHONDA)', 'NUEVO COLON', 'TASCO', 'MANTA', 'ANOLAIMA', 'JERICO', 'PUERTO SALGAR', 'CONDOTO', 'CERTEGUI', 'UBAQUE', 'MARIQUITA', 'BELEN DE UMBRIA', 
            'EL CARMEN DE BOLIVAR', 'SAN JUAN NEPOMUCENO', 'MOMPOS', 'EL PEÑON', 'YOLOMBO', 'PUERTO INIRIDA', 'SAN MIGUEL (LA DORADA)', 'OSPINA PEREZ (VENECIA)', 'PUERTO CARREÑO', 
            'BUENAVISTA', 'BARBACOAS', 'GIRALDO', 'TENA', 'AGUA DE DIOS', 'PUEBLO BELLO', 'HATONUEVO', 'CERRO SAN ANTONIO', 'SILVIA', 'YACOPI', 'YACUANQUER', 'OBANDO', 'LOPEZ (MICAY)',
            'CAÑASGORDAS', 'SAN SEBASTIAN DE BUENAVISTA', 'AMAGA', 'GIRON', 'BURITICA', 'VALDIVIA', 'GUAITARILLA', 'SAN BERNARDO', 'NARIÑO', 'ALDANA', 'UNGUIA', 'PUERTO ESCONDIDO',
            'SAN MARCOS', 'GUAPOTA', 'EL ROSAL', 'SUPIA', 'SANTA ROSA DEL SUR', 'EL CHARCO', 'PLANETA RICA', 'PURISIMA', 'BARRANCAS', 'PATIA (EL BORDO)', 'CABRERA', 'TOCA',
            'LA LLANADA', 'LLORO', 'SAN ROQUE', 'CHIGORODO', 'MACHETA', 'MAHATES', 'CUMARAL', 'PUERRES', 'PUPIALES', 'RICAURTE', 'EL CAIRO', 'CONVENCION', 'TAMESIS', 'FIRAVITOBA', 
            'COLON', 'CAIMITO', 'RAFAEL REYES (APULO)', 'TAME', 'NEIRA', 'LOS CORDOBAS', 'ALBAN', 'TOCAIMA', 'ARBOLEDA (BERRUECOS)', 'SAN LORENZO', 'URIBIA', 'SUAN', 'AYAPEL',
            'puerto COLOMBIA', 'CORRALES', 'VIOTA', 'YAGUARA', 'ANSERMANUEVO', 'SANTA FE DE ANTIOQUIA', 'TOLU', 'NECHI', 'LEBRIJA', 'TUCHIN', 'SAN JOSE DEL GUAVIARE', 'GUATAVITA', 
            'CHACHAGUI', 'SANDONA', 'ALTO BAUDO (PIE DE PATO)', 'COTORRA', 'TELLO', 'LA BELLEZA', 'ARBOLETES', 'YARUMAL', 'TARAZA', 'SASAIMA', 'VIANI', 'LABATECA', 'MUTISCUA',
            'SALGAR', 'VALENCIA', 'TAMINANGO', 'SAMPUES', 'SANTA BARBARA (ISCUANDE)', 'IMUES', 'CURUMANI', 'ARIGUANI (EL DIFICIL)', 'CANTON DE SAN PABLO (MANAGRU)', 'PALMITO',
            'EL PEÑOL', 'FRESNO', 'SEVILLA', 'GUAPI', 'SAN JUAN DE BETULIA', 'CACHIPAY', 'SAN VICENTE DE CHUCURI', 'GUARANDA', 'COYAIMA', 'GIRARDOTA', 'SUAITA', 'MALAGA',
            'YAVARATE (CD)', 'MAJAGUAL', 'ROBERTO PAYAN (SAN JOSE)', 'GUATAQUI', 'SAN JUAN DE URABA', 'GUAYATA', 'GALERAS (NUEVA GRANADA)', 'SAN BERNARDO DEL VIENTO', 
            'DABEIBA', 'SARAVENA', 'HISPANIA', 'EL CARMEN DE ATRATO', 'MACEO', 'Galapa', 'SAN ANTONIO', 'PAILITAS', 'SABANA DE TORRES', 'CUCUNUBA', 'CHAPARRAL', 'SANTA ANA', 
            'TIQUISIO (PUERTO RICO)', 'CICUCO', 'VIGIA DEL FUERTE', 'SIMIJACA', 'SAN PELAYO', 'SAMANIEGO', 'GAMARRA', 'NATAGAIMA', 'SARDINATA', 'LA GLORIA', 'PUERTO LIBERTADOR',
            'TOLUVIEJO', 'PUEBLO NUEVO', 'ARAUQUITA', 'PUEBLO RICO', 'SAN ANDRES SOTAVENTO', 'MOÑITOS', 'SANTIAGO', 'CAJIBIO', 'CALDONO', 'SAN JACINTO', 'BELTRAN', 'AGUAZUL',
            'ZARZAL', 'PIJIÑO DEL CARMEN (PIJIÑO)', 'SUCRE', 'SAN CARLOS', 'CHIMA', 'ZAMBRANO', 'SOPLAVIENTO', 'COLOSO (RICAURTE)', 'GUASCA', 'CHIMICHAGUA', 'ARANZAZU',
            'PAMPLONITA', 'EL ROBLE', 'BOJACA', 'SAN ESTANISLAO', 'SAN FELIPE (CD)', 'PUERTO COLOMBIA (CD)', 'MAPIRIPANA (CD)', 'SAN ALBERTO', 'CARACOLI', 'BALBOA', 'ARENAL',
            'SAN ANTERO', 'MANI', 'COLON (GENOVA)', 'TARAIRA', 'REMEDIOS', 'SILOS', 'CHALAN', 'PLATO', 'LA VEGA', 'COVEÑAS', 'PUERTO WILCHES', 'RAMIRIQUI', 'SUSACON', 'ANZA', 'NEMOCON', 'UBALA',
            'PADILLA', 'LERIDA', 'PELAYA', 'OVEJAS', 'SAN BENITO ABAD', 'CAICEDONIA', 'GUAMAL', 'REMOLINO', 'LA PALMA', 'CORINTO', 'EL AGUILA', 'BOLIVAR', 'CARMEN DE CARUPA', 'MUTATA', 'CAICEDO', 
            'LA CELIA', 'BARICHARA', 'PUERTO PARRA', 'TAMALAMEQUE', 'MURINDO', 'MONTECRISTO', 'PINILLOS', 'ARROYOHONDO', 'NOBSA', 'MANAURE BALCON DEL CESAR', 'BOCHALEMA', 'PORE', 'FUNES',
            'PUERTO BERRIO', 'NECOCLI', 'SAN GIL', 'CHITAGA', 'PUERTO TRIUNFO', 'ROSAS', 'ALBAN (SAN JOSE)', 'MEDIO SAN JUAN', 'PUERTO BOYACA', 'LA APARTADA', 'HELICONIA', 'LOS ANDES (SOTOMAYOR)',
            'CONSACA', 'QUETAME', 'EBEJICO', 'ACHI', 'BETULIA', 'COVARACHIA', 'SANTA BARBARA', 'MARSELLA', 'EL MOLINO', 'LA CHORRERA (CD)', 'LA PAZ', 'CONCORDIA', 'URUMITA', 'SOLITA', 'EL DONCELLO', 
            'MESETAS', 'OIBA', 'ZARAGOZA', 'MERCADERES', 'BRICENO', 'SAN VICENTE', 'MORALES', 'LOS SANTOS', 'TAUSA', 'ENTRERRIOS', 'VENECIA', 'GALAN', 'PUERTO RICO', 'CASTILLA LA NUEVA', 'TIBASOSA', 
            'SIACHOQUE', 'PUERTO SANTANDER (CD)', 'RAGONVALIA', 'SOPETRAN', 'PEQUE', 'NOROSÌ', 'CARMEN DEL DARIEN', 'MOGOTES', 'SAN JOSE DEL FRAGUA', 'SANTA HELENA DEL OPON', 'SEGOVIA', 
            'BAJO BAUDO (PIZARRO)', 'MARIPI', 'HATO', 'ALPUJARRA', 'VILLAGARZON', 'MOMIL', 'CANTAGALLO', 'LEIVA', 'VALPARAISO', 'HATILLO DE LOBA', 'TIBANA', 'SAN JOSE DE URE', 'BITUIMA',
            'GOMEZ PLATA', 'GACHALA', 'URAMITA', 'TITIRIBI', 'ONZAGA', 'ABEJORRAL', 'PUERTO NARE (LA MAGDALENA )', 'CHINACOTA', 'SAN CAYETANO', 'ASTREA', 'OROCUE', 'RIOBLANCO', 'SUAZA',
            'GACHETA', 'FUQUENE', 'TARAPACA (CD)', 'BELEN DE LOS ANDAQUIES', 'SAN RAFAEL', 'ANORI', 'ORTEGA', 'EL CASTILLO', 'SAN PEDRO DE CARTAGO', 'LANDAZURI', 'CASABIANCA', 'SALDAÑA',
            'SANTO DOMINGO', 'CEPITA', 'DOLORES', 'URRAO', 'TARQUI', 'TARSO', 'FREDONIA', 'SAN JOSE DE LA MONTANA', 'OLAYA', 'VILLAVIEJA', 'ACANDI', 'MARGARITA', 'NIMAIMA', 'VALLE DE SAN JOSE',
            'SOATA', 'SAN JACINTO DEL CAUCA', 'NUEVA GRANADA', 'SORACA', 'TUTA', 'BELMIRA', 'SANTA BARBARA DE PINTO', 'SAN ZENON', 'QUEBRADANEGRA', 'CUBARRAL', 'SAN JERONIMO', 'MONGUI', 
            'CARTAGENA DEL CHAIRA', 'PEDRAZA', 'MONTERREY', 'PUERTO CAICEDO', 'LA PRIMAVERA', 'VERSALLES', 'ANZOATEGUI', 'PITAL', 'SAN JOAQUIN', 'CAMPAMENTO', 'ARBOLEDAS', 'QUINCHIA', 
            'TALAIGUA NUEVO', 'HERVEO', 'CHIVOLO', 'SABOYA', 'LA MONTANITA', 'FOSCA', 'EL PAUJIL', 'MORELIA', 'LIBORINA', 'NOVITA', 'SUAREZ', 'BUESACO', 'PURIFICACION', 'LA VICTORIA', 
            'PACORA', 'LA SIERRA', 'AGUADA', 'CALIFORNIA', 'SAN CALIXTO', 'TORIBIO', 'ALGARROBO', 'SIBUNDOY', 'ARCABUCO', 'HATO COROZAL', 'MAPIRIPAN', 'AMALFI', 'MATANZA', 'NUQUI', 
            'EL TARRA', 'DURANIA', 'HOBO', 'CAPARRAPI', 'ARBELAEZ', 'PANDI', 'GENOVA', 'SAN JOSE DE MIRANDA', 'PAEZ', 'SALAMINA', 'JAMBALO', 'ALTOS DEL ROSARIO', 'ABRIAQUI', 'COLOMBIA', 
            'PEÑOL', 'IZA', 'LA ESPERANZA', 'BELALCAZAR', 'UTICA', 'LA ARGENTINA', 'ALTAMIRA', 'YONDO (CASABE)', 'CHIQUIZA', 'CARMEN DE APICALA', 'GRAMALOTE', 'SALENTO', 'ARATOCA', 
            'EL GUAMO', 'APIA', 'EL PLAYON', 'VELEZ', 'GUACHETA', 'AMBALEMA', 'SANTA CRUZ (GUACHAVES)', 'TERUEL', 'QUIPAMA', 'GUADALUPE', 'LA MERCED', 'GUALMATAN', 'IQUIRA', 'SOLANO',
            'FUENTE DE ORO', 'TRINIDAD', 'CUITIVA', 'LA PINTADA', 'LA JAGUA DEL PILAR', 'CARCASI', 'ICONONZO', 'TANGUA', 'ZAPATOCA', 'ALVARADO', 'PESCA', 'TORO', 'TEORAMA', 'CAJAMARCA', 
            'TENERIFE', 'CURILLO', 'EL CARMEN', 'EL CARMEN DE CHUCURI', 'REGIDOR', 'MOTAVITA', 'PRADO', 'MILAN', 'PARAMO', 'BARAYA', 'VERGARA', 'GAMA', 'VENADILLO', 'SAN MARTIN DE LOBA',
            'BETANIA', 'CAROLINA', 'SAN BENITO', 'SANTA MARIA', 'LA UVITA', 'CONFINES', 'VALLE DE SAN JUAN', 'EL GUACAMAYO', 'PINCHOTE', 'UMBITA', 'ILES', 'FORTUL', 'RIO VIEJO', 'ZETAQUIRA', 
            'PACHAVITA', 'COROMORO', 'GUAVATA', 'LA PEDRERA (CD)', 'TONA', 'ARMERO (GUAYABAL)', 'SABANAS DE SAN ANGEL', 'VETAS', 'CHIPATA', 'SAN PABLO DE BORBUR', 'SAPUYES', 'GUACA', 'BUCARASICA', 'PALOCABILDO', 'CUCUTILLA', 'VILLA CARO', 'LOURDES', 'GUAYABETAL', 'PURACE', 'ELIAS', 'CARAMANTA', 'ZAPAYAN', 'INZA', 'OTANCHE', 'NOCAIMA', 'MOLAGAVITA', 'ALEJANDRIA', 'TOPAGA', 'SATIVASUR', 'TOTA', 'SOTARA', 'SUPATA', 'GUACAMAYAS', 'CUMARIBO', 'CUNDAY', 'CAPITANEJO', 'SOTAQUIRA', 'JARDIN', 'PIJAO', 'PARATEBUENO', 'CONTRATACION', 'RIOFRIO', 'CHARALA', 'HACARI', 'HERRAN', 'EL ESPINO', 'CHITA', 'CIENEGA', 'SUTATAUSA', 'GAMEZA', 'SAN LUIS DE PALENQUE', 'ANGELOPOLIS', 'VISTAHERMOSA', 'JENESANO', 'RAQUIRA', 'LA MACARENA', 'COELLO', 'BOAVITA', 'PAZ DE RIO', 'SATIVANORTE', 'GUATICA', 'MISTRATO', 'CHISCAS', 'LEJANIAS', 'SAN LUIS DE GACENO', 'CHIVATA', 'EL COCUY', 'SAN JOSE DE PARE', 'PAJARITO', 'VILLAHERMOSA', 'BOYACA', 'PUERTO CONCORDIA', 'EL RETORNO', 'CACHIRA', 'VICTORIA', 'CERRITO', 'SALAZAR', 'CHITARAQUE', 'EL TABLON', 'POLICARPA', 'OSPINA', 'CERINZA', 'GACHANTIVA', 'PANQUEBA', 'LITORAL DEL BAJO SAN JUAN', 'SIPI', 'SIMITI', 'TESALIA', 'FLORIAN', 'SAN JOSE', 'VEGACHI', 'ATACO', 'ENCINO', 'PIAMONTE', 'BARRANCA DE UPIA', 'QUIPILE', 'SAN FERNANDO', 'RECETOR', 'GAMBITA', 'SUSA', 'PUERTO LLERAS', 'EL DORADO', 'CARURU', 'FILADELFIA', 'EL ROSARIO', 'BARRANCO MINAS (CD)', 'MONGUA', 'LA URIBE', 'MACARAVITA', 'YALI', 'ENCISO', 'TUNUNGUA', 'MARULANDA', 'TIBACUY', 'LA CAPILLA', 'PULI', 'SANTA ISABEL', 'GUEPSA', 'SACAMA', 'SACHICA', 'PUENTE NACIONAL', 'FALAN', 'SANTA ROSALIA', 'MEDINA', 'PUEBLORRICO', 'PUERTO RONDON', 'JURADO', 'PENSILVANIA', 'PALMAR', 'FLORESTA', 'OCAMONTE', 'SIMACOTA', 'SAN SEBASTIAN', 'NUNCHIA', 'SUTATENZA', 'PACOA (CD)', 'TAMARA', 'BERBEO', 'PALMAS SOCORRO', 'PANA PANA (CAMPO ALEGRE) (CD)', 'SURATA', 'JESUS MARIA', 'CHARTA', 'TIBIRITA', 'TUTAZA', 'SOCOTA', 'GUAYABAL DE SIQUIMA', 'CHAMEZA', 'SORA', 'SAN MIGUEL', 'JERUSALEN', 'LA SALINA', 'EL CALVARIO', 'BUSBANZA', 'PAIME', 'CRAVO NORTE', 'GUICAN', 'MACANAL', 'SAN JOSE DEL PALMAR', 'LABRANZAGRANDE', 'CHINAVITA', 'SOMONDOCO', 'MURILLO', 'CHIVOR', 'LA PEÑA', 'ALMEIDA', 'SAN MATEO', 'PISBA', 'ALMAGUER', 'RONCESVALLES', 'TOPAIPI', 'RONDON', 'SAN EDUARDO', 'CHAGUANI', 'EL ENCANTO (CD)', 'BETEITIVA', 'JORDAN', 'GUTIERREZ']

        mongo_uri = environ.get('MONGO_URI')
        connect(host=mongo_uri)

        for name in regions:
            reg = Region()
            reg.active=True
            reg.hash=sha256(f"{name}".encode('utf-8')).hexdigest()
            reg.name=name

            reg.save()
        print(f"{len(regions)} regions has been  inserted")